### ISSUE TITLE
Please fix multi-line URLs in templates

### ISSUE THREAD

**Issue by roncli** [underfisk/blizzhub-ts#1] opened 2018-11-27 12:28 UTC
For example, in diablo3.js, you have a URL inside a template, but the template has a line break in the middle of it:

```
            this.getApiHero = (region, bnet, heroId, locale) => {
                return httpRequest_1.HttpRequest.get(`https://${region}.api.blizzard.com/d3/profile/${bnet}/hero/${heroId}
                ?locale=${locale}&access_token=${this.token.identifier}`);
            };
```

This is causing the library to *actually insert a line break* in the URL, which results in a 404 from Blizzard.  To fix this, don't use line breaks inside templates when defining URLs:

```
            this.getApiHero = (region, bnet, heroId, locale) => {
                return httpRequest_1.HttpRequest.get(`https://${region}.api.blizzard.com/d3/profile/${bnet}/hero/${heroId}?locale=${locale}&access_token=${this.token.identifier}`);
            };
```

This type of error occurs in a whole bunch of places in diablo3.js and wow.js.  I wanted to do a pull request for this, but apparently wow.js is missing from this repository.  Please fix!

**Comment by roncli** [comment] 2018-11-27 12:39
Just noticed the project is in TypeScript, so the issues will need to be fixed there.  For instance:

```
        getApiHero = (region: string, bnet: string, heroId: string, locale: string): Promise<JSON | ApiException> => {
            return HttpRequest.get(`https://${region}.api.blizzard.com/d3/profile/${bnet}/hero/${heroId}
                ?locale=${locale}&access_token=${this.token.identifier}`)
        }
```

will become:

```
        getApiHero = (region: string, bnet: string, heroId: string, locale: string): Promise<JSON | ApiException> => {
            return HttpRequest.get(`https://${region}.api.blizzard.com/d3/profile/${bnet}/hero/${heroId}?locale=${locale}&access_token=${this.token.identifier}`)
        }
```

Thanks :)

**Comment by underfisk** [comment] 2018-11-27 12:46
Hi thanks for noticing that but when i used to test the API it was working and the new line was not being counted as a new line but i'll make them inline

**Comment by roncli** [comment] 2018-11-27 12:49
No worries, and thanks for getting this library up and running, I was pretty close to trying to make one myself before I found this!

Perhaps this is a Windows vs Mac/Linux line ending issue?  I am on Windows (I also have a Mac, but haven't tested this there just yet).

**Comment by underfisk** [comment] 2018-11-27 12:50
Maybe, i currently use debian to develop some of my major libs.
I'll make asap a fix for this, thanks for sharing it

**Comment by underfisk** [comment] 2018-12-15 23:40
Sorry for delay, i've updated this path problem just take a look at new update

**Closed as completed by underfisk** 2018-12-15 23:40 UTC

**Comment by roncli** [comment] 2019-01-06 03:21
Hi there, you missed one!  Check the `getApiHero` method of diablo3.js.

**Comment by underfisk** [comment] 2019-01-06 11:32
The issue is fixed, thanks for the report 👍
